### ISSUE TITLE
[TASK](ui): Migrate Switch component to TypeScript 

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#255]
### Task Description

We need to convert Switch and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**

- Check files that used with Switch, SwitchRow

**Sub-tasks**

- [x] change the name to .tsx of all related components
- [x] Change the stories to .tsx and all related componetns
- [x] fix all errors related to npm run typecheck
- [x] Transfer all related tests to vitests from jest
- [x] Check if npm run build is working and prove the working parts in storybook or example app
- [x] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.

**Comment by guoda-puidokaite** [comment]
**Bug Found** 🐞

**Issue:** Component can be `valid` and `invalid` at the same time, displaying icons for both states and applying the valid state switch outline
**Explanation**: See screenshot. Bug in current code base on the left, screenshot of possible fix on the right
<img width="1558" alt="Screenshot 2024-11-05 at 09 31 53" src="https://github.com/user-attachments/assets/21049bc1-2222-41d9-af20-b747872d128b">
<img width="1728" alt="Screenshot 2024-11-05 at 09 36 46" src="https://github.com/user-attachments/assets/677be0cc-68ca-4caf-8c1b-493c0e2b3243">
**Question:** How should this case be handled? Should `valid` or `invalid` take precedence?
**Fix:** Can fix in the Typescript migration PR and add a unit test. Otherwise, will raise a ticket.

CC: @edda

**Comment by guoda-puidokaite** [comment]
**Future Improvements 🚀**

- **Required Indicator**: A `required` indicator ensures that users complete all necessary fields before submission. I wonder if it make sense for a toggle to have a `required` icon if it’s always in an `on` or `off` state (`off` by default)? I’d recommend having a `required` icon + error/info message stating “Field is required” (or similar) only when the user hasn’t filled the field, but it’s necessary to proceed. This should disappear once the condition is fulfilled. Otherwise, the icon isn’t self explanatory  on its own UX-wise (colour, no message etc) and sticks around, even when the condition is fulfilled.
- **Prop Naming**: Could we make `helptext`, `errortext`. and `successtext` camel case, aligning with other props and JS/TS naming conventions?

See screenshot:
<img width="1099" alt="Screenshot 2024-11-05 at 09 44 14" src="https://github.com/user-attachments/assets/80ffbe03-89ae-4262-b71b-a1992d947efd">

**Comment by edda** [comment]
> **Bug Found** 🐞
> 
> **Issue:** Component can be `valid` and `invalid` at the same time, displaying icons for both states and applying the valid state to the switch outline. **Explanation**: See screenshot. Because there's two props called `valid` and `invalid`, the below bug is possible. <img alt="Screenshot 2024-11-05 at 10 32 17" width="1584" src="https://private-user-images.githubusercontent.com/121792659/383086829-04edd874-e293-4d6b-ae69-f08b6e0ee016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDIzOTIsIm5iZiI6MTczMDgwMjA5MiwicGF0aCI6Ii8xMjE3OTI2NTkvMzgzMDg2ODI5LTA0ZWRkODc0LWUyOTMtNGQ2Yi1hZTY5LWYwOGI2ZTBlZTAxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMDIxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjg1ZTM4MTIzZWQ2YzFmYmQ5MDEwNzcwYzhjZjQzYWQ2ZjRhZGMxMWY0ZTVkMzk4MjRlMzFlMDk4YmM3ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cfTxES2R2mvR4rlhqDoyu5lEFCarseXo5ztF0Ph2VMk"> **Fix:** We should combine `valid` and `invalid` into a single state to prevent redundancy and therefore, this bug. **UX Improvements**: See [#255 (comment)](https://github.com/cloudoperators/juno/issues/255#issuecomment-2456596321)
> 
> CC: @edda

It was a conscious decision to separate the valid/invalid props. The reason is that it is not a boolean valid/invalid. `invalid` is for form validations (e.g. a mandatory field wasn't filled, a field was filled in the wrong format, etc.). The `valid` prop is **not** the inverse of `invalid`, i.e. if something ceases to be `invalid` (because the user corrected their input) you're not meant to switch to the `valid` state, instead you simply deactivate the `invalid` state. The `valid` state is only meant to be used for very specific validations like e.g. a password field where you choose a new password and it has complex password rules. In that case you can use the `valid` state to show the user that what they entered fullfills the rules. However the `valid` state should not be used for everything that is valid in a form, because this would apply to almost anything, so you would have green borders and checkmarks on all the form elements and then it's better not to specifically highlight valid state to reduce visual clutter. This will also be explained in our design document.

**Comment by guoda-puidokaite** [comment]
Hey, @edda. The main issue stated was about the `valid` and `invalid` states being applied at the same time. The latter was just a suggestion. Do you think the stated bug is indeed a bug or expected?

**Comment by edda** [comment]
@guoda-puidokaite essentially it's more a matter of trusting people to use it correctly. We could think about changing it in such a way that if both are true, only `invalid` is respected. But we'll have to do this change for all form components that have the invalid and valid states then. So I'd say, add it to the collection epic for possible future improvements :D

**Comment by guoda-puidokaite** [comment]
Thanks, @edda. I added some possible improvement suggestions form my side [here](https://github.com/cloudoperators/juno/issues/255#issuecomment-2456596321).
